[project]
name = "own-git"
version = "0.1.0"
description = ""
authors = [
    {name = "MuratovER",email = "e.muratov@kanavto.ru"}
]
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "ruff (>=0.9.0,<0.10.0)",
    "mypy (>=1.14.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
